### ISSUE TITLE
about the meQTL

### ISSUE THREAD

**Issue by zhouxiaohong15** [douglasyao/mesc#6]
hello,this paper is useful for me, I have a question that "This analysis should be performed with all cis-eQTL summary statistics (including those that are non-significant). If you run this analysis…" in your github. Why? eQTL( But the P value of SNP-Gene pairs always < 1e-8).

I wonder if  1000 SNPs were  within 1 Mb of a gene TSS, then 1000 eQTL summary statistics should  be included in MESC analysis even if only few are significant?

**Comment by douglasyao** [comment]
Hi,

Thanks for checking out the paper. Yes, this analyses requires that all
cis-eQTL summary statistics be included in the analysis, including
non-significant ones. This is just how the method works - the quantity
being estimated requires this full information.
