### ISSUE TITLE
"h2med" and "h2med_over_h2med(tot)" are negative

### ISSUE THREAD

**Issue by moonwjy2021** [douglasyao/mesc#7]
.categories.h2med:
h2med: h2med estimate for gene category
h2med_over_h2med(tot): Proportion of total h2med explained by gene category

Gene_category	Num_genes	Prop_genes	Ave_h2cis	h2med	SE(h2med)	h2med_over_h2med(tot)	SE(h2med_over_h2med(tot))	h2med_enrichment	SE(h2med_enrichment)	h2med_enrichment_pvalue	Coefficient	SE(Coefficient)
h2cis_bin_1	3314	0.2003	0.01244	-0.001489	0.0030729	-0.1918	0.4436	-0.9575	2.2144	0.316690	-8.987e-06	1.855e-05
h

"h2med" and "h2med_over_h2med(tot)" are negative, so confused.... Proportion is negative, why?

Thanks!!

**Comment by nadineparker** [comment]
Hi,
I also have this issue with some of my analyses. It also results in h2med enrichments that are negative and can also be significant.

**Comment by moonwjy2021** [comment]
This is also the case in the reference article for this tool, in the extension figure. I think it may be because some analysis tissues and target tissues are quite different.

**Comment by douglasyao** [comment]
Hi,

Negative values for h2med and h2med_over_h2med(tot) can arise due to
sampling noise, which can be due to insufficient sample size for the eQTL
or GWAS dataset. In theory, it shouldn't be possible to get *significantly*
negative estimates, but this still happens from time to time (indicating
some pvalue miscalibration which we don't fully understand. We weren't able
to replicate it in simulations).

-Doug

**Comment by moonwjy2021** [comment]
Thank you very much for your answer !!


| |
weijingyue2021
|
|
***@***.***
|
签名由网易邮箱大师定制


On 09/5/2022 09:01，Douglas ***@***.***> wrote：

Hi,

Negative values for h2med and h2med_over_h2med(tot) can arise due to
sampling noise, which can be due to insufficient sample size for the eQTL
or GWAS dataset. In theory, it shouldn't be possible to get *significantly*
negative estimates, but this still happens from time to time (indicating
some pvalue miscalibration which we don't fully understand. We weren't able
to replicate it in simulations).

-Doug

**Comment by moonwjy2021** [comment]
This is also the case in the reference article for this tool, in the extension figure. I think it may be because some analysis tissues and target tissues are quite different.


| |
weijingyue2021
|
|
***@***.***
|
签名由网易邮箱大师定制


On 09/1/2022 ***@***.***> wrote：

Hi,
I also have this issue with some of my analyses. It also results in h2med enrichments that are negative and can also be significant.
