### ISSUE TITLE
Question about SNP ID

### ISSUE THREAD

**Issue by nadineparker** [douglasyao/mesc#8]
Hi,
I was wondering if MESC can handle variant IDs such as chromosome_ position_a1_a2 instead of rsid? Also, are duplicated rsid per gene a problem?

Nadine

**Comment by douglasyao** [comment]
Hi Nadine,

MESC can only handle rsIDs at the moment. I'm not sure if duplicate rsIDs
will lead to an error, but I would remove the duplicates to be safe.

-Doug

**Comment by nadineparker** [comment]
Thanks for the reply. I have one more question. Does MESC account for the potential that different genomic builds (hg19 vs hg38) can be used for eQTL and GWAS sumstats? Or as a user do we have to align the sumstats to one particular build?

**Comment by nadineparker** [comment]
Thanks for the reply. I have one more question. Does MESC account for the potential that different genomic builds (hg19 vs hg38) can be used for eQTL and GWAS sumstats? Or as a user do we have to align the sumstats to one particular build?

**Comment by douglasyao** [comment]
No problem. Either hg19 or hg38 should work.
